import type { Metadata } from "next";

import { FactList, InfoBody, InfoHero, InfoSection } from "@/components/marketing/InfoPage";
import { Alert } from "@/components/ui/Alert";
import { BRAND } from "@/lib/brand";

export const metadata: Metadata = { title: "Terms" };

const HOW_IT_WORKS = [
  {
    term: "The service",
    detail:
      "An AI receptionist that answers calls to your receptionist’s phone number, holds a conversation using the business details you provide, and produces a summary of each call.",
  },
  {
    term: "Your details",
    detail:
      "The receptionist relies on the information you enter during setup. Keeping your services, hours and escalation rules accurate helps it give callers correct answers.",
  },
  {
    term: "Summaries",
    detail:
      "Summaries are generated by AI from the conversation. Details such as callback numbers are recorded as stated by the caller and are not verified.",
  },
  {
    term: "Plans and usage",
    detail:
      "Each plan includes a number of call minutes per billing period. New accounts start on a free trial, which stops taking calls once its included minutes are used.",
  },
] as const;

export default function TermsPage() {
  return (
    <>
      <InfoHero
        eyebrow="Terms"
        title="Terms at a glance"
        intro={`A plain-language overview of how ${BRAND.name} works.`}
      />
      <InfoBody>
        <Alert tone="info" title="This is an overview, not our terms of service">
          The full terms of service will be published on this page. This overview does not replace them.
        </Alert>

        <InfoSection id="overview" title="How the service works">
          <FactList items={HOW_IT_WORKS} />
        </InfoSection>

        <InfoSection id="questions" title="Questions">
          <p>
            If anything here is unclear, please get in touch through our contact page before you rely on it.
          </p>
        </InfoSection>
      </InfoBody>
    </>
  );
}
