"""poc provisioning support

Schema additions the remaining POC modules need. Autogenerated, then corrected
by hand in three places that autogenerate gets wrong:

* ``calls.attempt`` is NOT NULL, so it is added with a server default and the
  default is then dropped — otherwise the migration fails on a populated table.
* ``business_profiles.greeting_style`` becomes an enum. Existing NULLs are
  backfilled first, and the CHECK constraint is created explicitly: Alembic
  emits the ``ALTER COLUMN TYPE`` for a non-native enum but never the constraint
  that gives it meaning, and it does not autogenerate CHECK constraints either,
  so nothing would have noticed it missing.
* The reverse of both is spelled out in ``downgrade``.

Additions:
  webhook_events                    durable webhook dedupe + audit trail
  business_profiles.greeting_style  free text -> enum (selects the voice)
  phone_numbers.elevenlabs_phone_id ElevenLabs' own id for an imported number
  calls.attempt/next_attempt_at/last_error  retry bookkeeping for summarization

Revision ID: 6c1f0a7b91d2
Revises: a0527c9bd742
Created: 2026-09-06 03:17
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6c1f0a7b91d2"
down_revision: str | None = "a0527c9bd742"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

GREETING_STYLES = ("professional", "friendly", "formal")
_GREETING_CHECK = "greeting_style IN ('professional', 'friendly', 'formal')"


def upgrade() -> None:
    op.create_table(
        "webhook_events",
        sa.Column(
            "provider",
            sa.Enum("elevenlabs", "twilio", name="webhook_provider", native_enum=False, length=48),
            nullable=False,
        ),
        sa.Column("event_id", sa.String(length=200), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "processed",
                "duplicate",
                "rejected",
                "failed",
                name="webhook_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
        sa.UniqueConstraint("provider", "event_id", name="uq_webhook_events_provider_event_id"),
    )
    op.create_index(
        "ix_webhook_events_provider_status", "webhook_events", ["provider", "status"], unique=False
    )

    # greeting_style: free text -> constrained enum.
    op.execute(
        "UPDATE business_profiles SET greeting_style = 'professional' "
        f"WHERE greeting_style IS NULL OR greeting_style NOT IN {GREETING_STYLES}"
    )
    op.alter_column(
        "business_profiles",
        "greeting_style",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=48),
        nullable=False,
    )
    op.create_check_constraint("greeting_style", "business_profiles", _GREETING_CHECK)

    # calls: retry bookkeeping for summarization.
    op.add_column(
        "calls", sa.Column("attempt", sa.Integer(), nullable=False, server_default=sa.text("0"))
    )
    op.alter_column("calls", "attempt", server_default=None)
    op.add_column("calls", sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("calls", sa.Column("last_error", sa.Text(), nullable=True))
    op.create_index(
        "ix_calls_status_next_attempt_at", "calls", ["status", "next_attempt_at"], unique=False
    )

    # phone_numbers: the ElevenLabs-side identifier for an imported number.
    op.add_column("phone_numbers", sa.Column("elevenlabs_phone_id", sa.String(length=64)))
    op.create_unique_constraint(
        op.f("uq_phone_numbers_elevenlabs_phone_id"), "phone_numbers", ["elevenlabs_phone_id"]
    )


def downgrade() -> None:
    op.drop_constraint(
        op.f("uq_phone_numbers_elevenlabs_phone_id"), "phone_numbers", type_="unique"
    )
    op.drop_column("phone_numbers", "elevenlabs_phone_id")

    op.drop_index("ix_calls_status_next_attempt_at", table_name="calls")
    op.drop_column("calls", "last_error")
    op.drop_column("calls", "next_attempt_at")
    op.drop_column("calls", "attempt")

    # Bare name: the metadata naming convention expands it, and passing the
    # expanded name would get the prefix applied twice.
    op.drop_constraint("greeting_style", "business_profiles", type_="check")
    op.alter_column(
        "business_profiles",
        "greeting_style",
        existing_type=sa.String(length=48),
        type_=sa.VARCHAR(length=64),
        nullable=True,
    )

    op.drop_index("ix_webhook_events_provider_status", table_name="webhook_events")
    op.drop_table("webhook_events")
