"""initial schema

The eight POC tables from docs/01_PLAN_POC.md, and the constraints that make the
provisioning workflow safe to retry:

* ``uq_phone_numbers_active_per_tenant``   one live number per tenant
* ``uq_provisioning_steps_run_id_step_name``  a step exists once per run
* ``uq_calls_provider_call_id``            post-call webhook replay is a no-op
* ``uq_provisioning_runs_in_flight_per_tenant``  one live run per tenant, so two
  workers cannot both decide to buy a number
* ``uq_agent_configs_live_per_tenant``     one live config per tenant
* ``uq_tenants_live_contact_email``        one live signup per business

Enums are VARCHAR + CHECK rather than native Postgres types, so a later module
can add a provisioning step without an ``ALTER TYPE``.

Autogenerated, then reviewed by hand.

Revision ID: a0527c9bd742
Revises:
Created: 2026-09-06 02:53:44
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a0527c9bd742"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "business_type",
            sa.Enum(
                "salon",
                "legal",
                "medical",
                "real_estate",
                "other",
                name="business_type",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("contact_email", sa.String(length=320), nullable=False),
        sa.Column("contact_phone", sa.String(length=32), nullable=False),
        sa.Column("area_code", sa.String(length=3), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "plan",
            sa.Enum("trial", "starter", "pro", name="tenant_plan", native_enum=False, length=48),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "failed",
                "abandoned",
                "cancelled",
                name="tenant_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_index("ix_tenants_status", "tenants", ["status"], unique=False)
    op.create_index(
        "uq_tenants_live_contact_email",
        "tenants",
        ["contact_email"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'active')"),
    )
    op.create_table(
        "agent_configs",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("first_message", sa.Text(), nullable=False),
        sa.Column("voice_id", sa.String(length=64), nullable=True),
        sa.Column("model_params_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "generated_by",
            sa.Enum(
                "llm",
                "template_fallback",
                "manual",
                name="agent_config_source",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("generator_detail", sa.String(length=128), nullable=True),
        sa.Column("template_version", sa.String(length=32), nullable=True),
        sa.Column("is_live", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_agent_configs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_configs")),
        sa.UniqueConstraint("tenant_id", "version", name="uq_agent_configs_tenant_id_version"),
    )
    op.create_index(
        "uq_agent_configs_live_per_tenant",
        "agent_configs",
        ["tenant_id"],
        unique=True,
        postgresql_where=sa.text("is_live"),
    )
    op.create_table(
        "business_profiles",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("raw_form_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("services", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hours_raw", sa.Text(), nullable=True),
        sa.Column("hours_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("greeting_style", sa.String(length=64), nullable=True),
        sa.Column("escalation_raw", sa.Text(), nullable=True),
        sa.Column("escalation_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("config_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_business_profiles_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_profiles")),
        sa.UniqueConstraint("tenant_id", name=op.f("uq_business_profiles_tenant_id")),
    )
    op.create_table(
        "calls",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("provider_call_id", sa.String(length=128), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("inbound", "outbound", name="call_direction", native_enum=False, length=48),
            nullable=False,
        ),
        sa.Column("from_e164", sa.String(length=20), nullable=True),
        sa.Column("to_e164", sa.String(length=20), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_s", sa.Integer(), nullable=True),
        sa.Column("transcript_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("caller_name", sa.String(length=200), nullable=True),
        sa.Column("callback_number", sa.String(length=32), nullable=True),
        sa.Column("intent", sa.String(length=64), nullable=True),
        sa.Column("urgency", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "transcribed",
                "summarized",
                "notified",
                "failed",
                name="call_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_s IS NULL OR duration_s >= 0", name=op.f("ck_calls_duration_not_negative")
        ),
        sa.CheckConstraint(
            "urgency IS NULL OR (urgency >= 1 AND urgency <= 5)",
            name=op.f("ck_calls_urgency_within_range"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_calls_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calls")),
        sa.UniqueConstraint("provider_call_id", name=op.f("uq_calls_provider_call_id")),
    )
    op.create_index(
        "ix_calls_tenant_id_started_at", "calls", ["tenant_id", "started_at"], unique=False
    )
    op.create_table(
        "phone_numbers",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("e164", sa.String(length=20), nullable=False),
        sa.Column("twilio_sid", sa.String(length=64), nullable=True),
        sa.Column("area_code", sa.String(length=3), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "released",
                "failed",
                name="phone_number_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("purchased_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'released' OR released_at IS NOT NULL",
            name=op.f("ck_phone_numbers_released_at_required_once_released"),
        ),
        sa.CheckConstraint(
            "status = 'pending' OR twilio_sid IS NOT NULL",
            name=op.f("ck_phone_numbers_twilio_sid_required_once_purchased"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_phone_numbers_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phone_numbers")),
        sa.UniqueConstraint("twilio_sid", name=op.f("uq_phone_numbers_twilio_sid")),
    )
    op.create_index(
        "uq_phone_numbers_active_e164",
        "phone_numbers",
        ["e164"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "uq_phone_numbers_active_per_tenant",
        "phone_numbers",
        ["tenant_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "provisioning_runs",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "validated",
                "config_generated",
                "number_purchased",
                "agent_created",
                "number_linked",
                "verified",
                "active",
                "failed",
                "compensating",
                "compensated",
                name="provisioning_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "current_step",
            sa.Enum(
                "validate",
                "generate_config",
                "purchase_number",
                "create_agent",
                "link_number",
                "verify",
                "activate",
                name="provisioning_step",
                native_enum=False,
                length=48,
            ),
            nullable=True,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_provisioning_runs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provisioning_runs")),
    )
    op.create_index(
        "ix_provisioning_runs_correlation_id", "provisioning_runs", ["correlation_id"], unique=False
    )
    op.create_index(
        "ix_provisioning_runs_status_next_attempt_at",
        "provisioning_runs",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_index(
        "uq_provisioning_runs_in_flight_per_tenant",
        "provisioning_runs",
        ["tenant_id"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('agent_created', 'compensating', 'config_generated', 'draft', 'number_linked', 'number_purchased', 'validated', 'verified')"
        ),
    )
    op.create_table(
        "agents",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("agent_config_id", sa.UUID(), nullable=False),
        sa.Column("elevenlabs_agent_id", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "failed",
                "deleted",
                name="agent_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_config_id"],
            ["agent_configs.id"],
            name=op.f("fk_agents_agent_config_id_agent_configs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_agents_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
        sa.UniqueConstraint("elevenlabs_agent_id", name=op.f("uq_agents_elevenlabs_agent_id")),
    )
    op.create_index(
        "uq_agents_active_per_tenant",
        "agents",
        ["tenant_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "provisioning_steps",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column(
            "step_name",
            sa.Enum(
                "validate",
                "generate_config",
                "purchase_number",
                "create_agent",
                "link_number",
                "verify",
                "activate",
                name="provisioning_step",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "skipped",
                name="step_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("response_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["provisioning_runs.id"],
            name=op.f("fk_provisioning_steps_run_id_provisioning_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provisioning_steps")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_provisioning_steps_idempotency_key")),
        sa.UniqueConstraint("run_id", "step_name", name="uq_provisioning_steps_run_id_step_name"),
    )


def downgrade() -> None:
    op.drop_table("provisioning_steps")
    op.drop_index(
        "uq_agents_active_per_tenant",
        table_name="agents",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("agents")
    op.drop_index(
        "uq_provisioning_runs_in_flight_per_tenant",
        table_name="provisioning_runs",
        postgresql_where=sa.text(
            "status IN ('agent_created', 'compensating', 'config_generated', 'draft', 'number_linked', 'number_purchased', 'validated', 'verified')"
        ),
    )
    op.drop_index("ix_provisioning_runs_status_next_attempt_at", table_name="provisioning_runs")
    op.drop_index("ix_provisioning_runs_correlation_id", table_name="provisioning_runs")
    op.drop_table("provisioning_runs")
    op.drop_index(
        "uq_phone_numbers_active_per_tenant",
        table_name="phone_numbers",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(
        "uq_phone_numbers_active_e164",
        table_name="phone_numbers",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("phone_numbers")
    op.drop_index("ix_calls_tenant_id_started_at", table_name="calls")
    op.drop_table("calls")
    op.drop_table("business_profiles")
    op.drop_index(
        "uq_agent_configs_live_per_tenant",
        table_name="agent_configs",
        postgresql_where=sa.text("is_live"),
    )
    op.drop_table("agent_configs")
    op.drop_index(
        "uq_tenants_live_contact_email",
        table_name="tenants",
        postgresql_where=sa.text("status IN ('pending', 'active')"),
    )
    op.drop_index("ix_tenants_status", table_name="tenants")
    op.drop_table("tenants")
